### ISSUE TITLE
Support @FindBy annotation with SelenideElement

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/masquerade#44]
```
@FindBy(className = 'v-grid-editor')
 SelenideElement gridEditor
```
```
java.lang.RuntimeException: Unable to instantiate composite com.codeborne.selenide.SelenideElement

	at com.haulmont.masquerade.Components.wireClassBy(Components.java:125)
	at com.haulmont.masquerade.Components.getTargetFieldValue(Components.java:186)
	at com.haulmont.masquerade.Components.wireClassBy(Components.java:131)
	at com.haulmont.masquerade.Components.wire(Components.java:78)
	at com.haulmont.masquerade.Components._$(Components.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206)
	at com.haulmont.rent.web.DataGridUiTest.checkInlineEditor(DataGridUiTest.groovy:119)com.haulmont.rent.web.rules.WebBrowserReuseRule$1.evaluate(WebBrowserReuseRule.groovy:24)

Caused by: java.lang.InstantiationException: com.codeborne.selenide.SelenideElement
	at java.lang.Class.newInstance(Class.java:427)
	at com.haulmont.masquerade.Components.wireClassBy(Components.java:123)
	... 55 more
Caused by: java.lang.NoSuchMethodException: com.codeborne.selenide.SelenideElement.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 56 more
```

### QA

Please consider that the original case is incorrect, because inline editor is not shown by default

**Comment by jreznot** [comment]
Components factory should check if field type is SelenideElement and create standard Selenide instance in this case.
